### ISSUE TITLE
SuperTuxKart add-on for Blender

### ISSUE THREAD

**Issue by ghost** [KillzXGaming/Mario-Kart-8-Blender-Path-XML-Exporter#1]
Maybe you also could help improve SuperTuxKart add-on for Blender
* https://github.com/leyyin/stk-blender

**Comment by KillzXGaming** [comment]
This generally does some basic exporting from blender functions with coordinates in a scene and just exports it. It's pretty simple stuff, i don't have much interest in other projects atm though I'm sure the person behind that tool has it under control. I'm also very new to all this so i'm not quite sure if i'd be up for the task.
